[package]
name = "tonic-mock"
version = "0.1.0"
authors = ["Tyr Chen <tyr.chen@gmail.com>"]
edition = "2018"
license = "MIT"
documentation = "https://docs.rs/tonic-mock"
repository = "https://github.com/tyrchen/tonic-mock"
homepage = "https://github.com/tyrchen/tonic-mock"
description = """
Test utilities for easy mocking tonic streaming interface
"""
readme = "README.md"
categories = ["development-tools"]
keywords = ["tonic", "testing"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.4.0"
futures = "0.3.26"
http-body = "0.4.5"
http = "0.2.9"
prost = "0.11"
tonic = "0.9"

[dev-dependencies]
async-stream = "0.3"
tokio = { version = "1", features = ["rt-multi-thread"] }
